CREATE TABLE comments (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id   BIGINT        NOT NULL REFERENCES tickets (id),
  body        VARCHAR(4000) NOT NULL,
  author_id   BIGINT        NOT NULL,
  created_at  TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chk_comments_body_len CHECK (char_length(btrim(body)) BETWEEN 1 AND 4000),
  CONSTRAINT chk_comments_author_id CHECK (author_id > 0)
);

CREATE INDEX idx_comments_ticket_id_created_at ON comments (ticket_id, created_at ASC);
